from datetime import UTC, datetime
from uuid import uuid4

from fastapi import FastAPI, File, HTTPException, UploadFile, status
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .imaging import InvalidImage, preprocess_image
from .schemas import AnalysisResult, InputSummary, OaPrediction, WarningItem


app = FastAPI(
    title="OrthoLens Research API",
    version="0.1.0",
    description="Research prototype. Not for clinical diagnosis.",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.origin_list,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["Content-Type"],
)


@app.get("/health")
def health() -> dict[str, str | bool]:
    return {"status": "ok", "service": "ortholens-api", "research_only": True}


@app.post("/v1/studies/analyse", response_model=AnalysisResult)
async def analyse(file: UploadFile = File(...)) -> AnalysisResult:
    content = await file.read(settings.max_upload_bytes + 1)
    if not content:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "The uploaded file is empty.")
    if len(content) > settings.max_upload_bytes:
        raise HTTPException(status.HTTP_413_REQUEST_ENTITY_TOO_LARGE, "The uploaded file exceeds the configured size limit.")
    try:
        image = preprocess_image(content)
    except InvalidImage as exc:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, str(exc)) from exc

    probabilities = {"0": 0.04, "1": 0.16, "2": 0.62, "3": 0.14, "4": 0.04}
    return AnalysisResult(
        study_id=f"demo-{uuid4().hex[:12]}",
        created_at=datetime.now(UTC),
        input=InputSummary(**image.__dict__),
        pipeline_version="preprocessing-0.1.0",
        prediction=OaPrediction(
            model_version="placeholder-not-trained",
            selected_kl_grade=2,
            probabilities=probabilities,
            uncertainty=0.38,
        ),
        warnings=[
            WarningItem(
                code="PLACEHOLDER_MODEL",
                severity="warning",
                message="These probabilities were not generated by a trained model.",
            ),
            WarningItem(
                code="RESEARCH_ONLY",
                severity="warning",
                message="Not for clinical diagnosis, triage, or treatment planning.",
            ),
        ],
    )

